### ISSUE TITLE
Document `invalidates`

### ISSUE THREAD

**Issue by JoeChapman** [UKHomeOffice/passports-form-wizard#55]
Add documentation for `invalidates`

**Comment by joefitter** [comment]
This is a feature built in to `check-progress` middleware which checks fields for an `invalidates` array. When the field is amended, all fields in `invalidates` are removed from the `sessionModel`.

This is a useful feature and one I have started using in GRO form migration but there doesn't seem to be any documentation around the feature (at least that I can find)

Something I wanted to check was the reasoning behind clearing future steps when an invalidating field is amended - https://github.com/UKHomeOffice/passports-form-wizard/blob/master/lib/middleware/check-progress.js#L53-L54 as the fields to invalidate may not necessarily be on any of the future steps, and an invalidating field could be changed after completing the form and visiting the confirm page, resulting in losing all future steps from the sessionModel.

A change I propose, relating to my PR https://github.com/UKHomeOffice/passports-form-wizard/pull/54, would be to check if all fields on a `step` have been invalidated, and if so then remove this step from the sessionModel, instead of removing all future steps.

I have added this as a PR in hof-controllers for now as it fixes a lot of bugs in GRO but I believe this is the best place for the logic to be altered due to it being a middleware. HOF-Controllers PR - https://github.com/UKHomeOffice/hof-controllers/pull/37
